apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: "2.x"
    registry: "ghcr.io/fluxcd"
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  cluster:
    type: kubernetes
    networkPolicy: true
  sync:
    kind: GitRepository
    url: "https://gitlab.com/${FLUX_GIT_REPO_OWNER}/${FLUX_GIT_REPO_NAME}.git"
    ref: "refs/heads/${FLUX_GIT_REPO_BRANCH}"
    path: "clusters/${CLUSTER_NAME}"
    pullSecret: "flux-system"
