apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: additional-manifests
  namespace: flux-system
spec:
  interval: 24h
  url: https://everythings-gonna-be-alright.github.io/fluxcd-helm-additional-manifests
