# This secret is created by the bootstrap script.
# This is just a template for the secret.
apiVersion: v1
kind: Secret
metadata:
  name: openclaw-envs
  namespace: openclaw
type: Opaque
stringData:
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  OPENCLAW_GATEWAY_TOKEN: ${OPENCLAW_GATEWAY_TOKEN}
