apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: openclaw
namespace: openclaw
resources:
  - namespace.yaml
  - helm-repository-openclaw.yaml
  - helm-release-openclaw.yaml
